version: 2.0
defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/buildpack-deps:stretch
      environment:
        IMAGE_NAME: ajochope/docker-react
jobs:
  build:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "19:af:41:7c:63:b6:22:d8:74:ee:eb:71:bd:ef:9a:cf"
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image
          command: | 
            docker push $IMAGE_NAME:$CIRCLE_SHA1
  frontend-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Run Test and Coverage
          command: |
            docker run -e CI=true $IMAGE_NAME:$CIRCLE_SHA1 npm run test -- --coverage
  upload-coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Script inside Droplet
          command: |
            ssh -v -o StrictHostKeyChecking=no root@ajochope.tk "/bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"
workflows:
  version: 2

  commit:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - frontend-tests:
          filters:
            branches:
              only: master
          requires:
             - build
      - upload-coverage:
          filters:
            branches:
              only: master
          requires:
             - frontend-tests